@startuml
skinparam componentStyle uml2
component CORE {
   package "core" {
   }
}
component JSON {
   package "json" {
   }
}
component UI {
   package "ui" {
   }
}

component [JACKSON] #Strategy
component [JavaFX] #Strategy

UI -[#blue]-> CORE
UI -[#blue]-> JSON
JSON -[#red]-> CORE

UI .[#red].> [JavaFX]
UI .[#red].> [JACKSON]
JSON .[#red].> [JACKSON]


@enduml