@startuml

'!include plantuml-ae.iuml

actor Alice #SaddleBrown

Alice -> ui: Input "ny regel;verdi"
ui -> BeerController: addRule() *click "Legg til" button*
BeerController -> IBeerMain: addRule()
IBeerMain -> BeerMainRemoteAccess:
BeerMainRemoteAccess -> Server: HTTP POST/action/?description="ny regel"&value="verdi"
Alice -> ui: Input "navn"
ui -> BeerController: addMember() *click "Legg til" button*
BeerController -> IBeerMain: addMember()
IBeerMain -> BeerMainRemoteAccess
BeerMainRemoteAccess -> Server: HTTP POST/action/?name="navn"




'!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml