@startuml

'!include plantuml-ae.iuml

actor Alice #SaddleBrown

Alice -> ui: Input "ny regel;verdi"
ui -> BeerController: addRule() *click "Legg til" button*
BeerController -> BeerMainRemoteAccess: addRule()
BeerMainRemoteAccess -> RestServer: HTTP POST/action/?description="ny regel"&value="verdi"
database Database
RestServer --> Database
BeerMainRemoteAccess -> RestServer: HTTP GET beerMain
RestServer --> Database
Database --> RestServer
RestServer --> BeerMainRemoteAccess: HTTP Response
BeerMainRemoteAccess --> BeerController
BeerController --> ui
ui --> Alice


'!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml